const cartTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    REDUCE_CART_ITEM: 'REDUCE_CART_ITEM',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    CLEAR_CART: 'CLEAR_CART',
    UPDATE_CART: 'UPDATE_CART'
};

export default cartTypes;
